#[derive(Debug, Clone, PartialEq)]
pub struct TokenWithPosition {
    pub token: Token,
    pub line: usize,
    pub column: usize,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    // Keywords
    Create,
    A,
    An,
    The,
    Called,
    Named,
    Database,
    DB,
    Collection,
    Collections,
    In,
    It,
    These,
    Show,
    Set,
    To,
    Is,
    Store,
    Save,
    Let,
    Make,
    True,
    False,
    Null,
    Insert,
    Add,
    Put,
    Into,
    From,
    Select,
    Get,
    Find,
    Fetch,
    All,
    Where,
    Update,
    Change,
    Modify,
    Delete,
    Remove,
    With,
    And,
    Of,
    // Authentication Keywords
    Signup,
    Login,
    Logout,
    User,
    Email,
    Password,
    Session,
    Token,
    // Testing Keywords
    Test,
    Assert,
    Expect,
    Should,
    Be,
    // File I/O Keywords
    Read,
    Write,
    Append,
    Open,
    Close,
    Server,
    Web,
    Start,
    On,
    Port,
    Route,
    Endpoint,
    Page,
    Website,
    App,
    API,
    Handle,
    Request,
    Response,
    Return,
    HTML,
    JSON,

    // HTML/UI Keywords
    Render,
    Component,
    Element,
    Div,
    Button,
    Form,
    Input,
    Label,
    Text,
    Link,
    Image,
    Video,
    Header,
    Footer,
    Nav,
    Section,
    Article,
    Aside,
    Main,
    Span,
    Paragraph,
    Heading,
    List,
    Item,
    Table,
    Row,
    Cell,
    Title,
    Body,
    Head,

    // CSS/Styling Keywords
    Style,
    Color,
    Background,
    Width,
    Height,
    Margin,
    Padding,
    Border,
    Font,
    Size,
    Bold,
    Italic,
    Underline,
    Align,
    Center,
    Left,
    Right,
    Top,
    Bottom,
    Flex,
    Grid,
    Display,
    Position,
    Float,
    Clear,
    Overflow,
    Cursor,
    Opacity,
    ZIndex,

    // UI Component Keywords
    Labeled,
    Placeholder,
    Src,
    Source,
    Alt,
    Icon,
    Asset,
    File,
    Path,
    Value,
    Type,
    Required,
    Disabled,
    Readonly,
    Hidden,
    Visible,
    Onclick,
    Onsubmit,
    Onchange,

    // Layout Keywords
    Container,
    Wrapper,
    Panel,
    Card,
    Modal,
    Sidebar,
    Content,
    Menu,
    Dropdown,
    Tooltip,
    Badge,
    Alert,
    Toast,
    Loading,
    Spinner,

    // Control Flow Keywords
    If,
    Then,
    Else,
    Otherwise,
    When,
    While,
    Loop,
    For,
    Each,
    Times,
    Repeat,
    Until,
    Break,
    Continue,
    Do,
    End,

    // Error Handling Keywords
    Try,
    Catch,
    Throw,
    Error,
    Finally,
    Raise,

    // Function Keywords
    Define,
    Function,
    Procedure,
    Takes,
    Parameters,
    Returns,
    Call,
    Invoke,
    Run,
    That,

    // Array & String Operation Keywords
    Push,
    Pop,
    Filter,
    Map,
    Sort,
    Reverse,
    Length,
    Contains,
    First,
    Last,
    Join,
    Split,
    Replace,
    Trim,
    Uppercase,
    Lowercase,
    Substring,
    IndexOf,
    Concat,
    Concatenate,

    // Comparison Operators (as words)
    EqualTo,
    NotEqualTo,
    GreaterThan,
    LessThan,
    GreaterThanOrEqual,
    LessThanOrEqual,
    Or,
    Not,

    // Literals
    String(String),
    Number(f64),
    Identifier(String),

    // Structure
    Newline,
    Comma,
    Equals,
    Dot,
    Minus,
    Plus,
    Star,
    Slash,
    Colon,
    LeftBracket,
    RightBracket,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    EOF,
}

impl Token {
    pub fn from_word(word: &str) -> Self {
        match word.to_lowercase().as_str() {
            "create" => Token::Create,
            "a" => Token::A,
            "an" => Token::An,
            "the" => Token::The,
            "called" => Token::Called,
            "named" => Token::Named,
            "database" => Token::Database,
            "db" => Token::DB,
            "collection" => Token::Collection,
            "collections" => Token::Collections,
            "in" => Token::In,
            "it" => Token::It,
            "these" => Token::These,
            "show" => Token::Show,
            "set" => Token::Set,
            "to" => Token::To,
            "is" => Token::Is,
            "store" => Token::Store,
            "save" => Token::Save,
            "let" => Token::Let,
            "make" => Token::Make,
            "true" => Token::True,
            "false" => Token::False,
            "null" => Token::Null,
            "insert" => Token::Insert,
            "add" => Token::Add,
            "put" => Token::Put,
            "into" => Token::Into,
            "from" => Token::From,
            "select" => Token::Select,
            "get" => Token::Get,
            "find" => Token::Find,
            "fetch" => Token::Fetch,
            "all" => Token::All,
            "where" => Token::Where,
            "update" => Token::Update,
            "change" => Token::Change,
            "modify" => Token::Modify,
            "delete" => Token::Delete,
            "remove" => Token::Remove,
            "with" => Token::With,
            "and" => Token::And,
            "of" => Token::Of,
            // Authentication
            "signup" => Token::Signup,
            "login" => Token::Login,
            "logout" => Token::Logout,
            "user" => Token::User,
            "email" => Token::Email,
            "password" => Token::Password,
            "session" => Token::Session,
            "token" => Token::Token,
            // Testing
            "test" => Token::Test,
            "assert" => Token::Assert,
            "expect" => Token::Expect,
            "should" => Token::Should,
            "be" => Token::Be,
            // File I/O
            "read" => Token::Read,
            "write" => Token::Write,
            "append" => Token::Append,
            "open" => Token::Open,
            "close" => Token::Close,
            "server" => Token::Server,
            "web" => Token::Web,
            "start" => Token::Start,
            "on" => Token::On,
            "port" => Token::Port,
            "route" => Token::Route,
            "endpoint" => Token::Endpoint,
            "page" => Token::Page,
            "website" => Token::Website,
            "app" => Token::App,
            "api" => Token::API,
            "handle" => Token::Handle,
            "request" => Token::Request,
            "response" => Token::Response,
            "return" => Token::Return,
            "html" => Token::HTML,
            "json" => Token::JSON,
            // HTML/UI Keywords
            "render" => Token::Render,
            "component" => Token::Component,
            "element" => Token::Element,
            "div" => Token::Div,
            "button" => Token::Button,
            "form" => Token::Form,
            "input" => Token::Input,
            "label" => Token::Label,
            "text" => Token::Text,
            "link" => Token::Link,
            "image" => Token::Image,
            "video" => Token::Video,
            "header" => Token::Header,
            "footer" => Token::Footer,
            "nav" => Token::Nav,
            "section" => Token::Section,
            "article" => Token::Article,
            "aside" => Token::Aside,
            "main" => Token::Main,
            "span" => Token::Span,
            "paragraph" => Token::Paragraph,
            "heading" => Token::Heading,
            "list" => Token::List,
            "item" => Token::Item,
            "table" => Token::Table,
            "row" => Token::Row,
            "cell" => Token::Cell,
            "title" => Token::Title,
            "body" => Token::Body,
            "head" => Token::Head,
            // CSS/Styling Keywords
            "style" => Token::Style,
            "color" => Token::Color,
            "background" => Token::Background,
            "width" => Token::Width,
            "height" => Token::Height,
            "margin" => Token::Margin,
            "padding" => Token::Padding,
            "border" => Token::Border,
            "font" => Token::Font,
            "size" => Token::Size,
            "bold" => Token::Bold,
            "italic" => Token::Italic,
            "underline" => Token::Underline,
            "align" => Token::Align,
            "center" => Token::Center,
            "left" => Token::Left,
            "right" => Token::Right,
            "top" => Token::Top,
            "bottom" => Token::Bottom,
            "flex" => Token::Flex,
            "grid" => Token::Grid,
            "display" => Token::Display,
            "position" => Token::Position,
            "float" => Token::Float,
            "clear" => Token::Clear,
            "overflow" => Token::Overflow,
            "cursor" => Token::Cursor,
            "opacity" => Token::Opacity,
            "zindex" => Token::ZIndex,
            // UI Component Keywords
            "labeled" => Token::Labeled,
            "placeholder" => Token::Placeholder,
            "src" => Token::Src,
            "source" => Token::Source,
            "alt" => Token::Alt,
            "icon" => Token::Icon,
            "asset" => Token::Asset,
            "file" => Token::File,
            "path" => Token::Path,
            "value" => Token::Value,
            "type" => Token::Type,
            "required" => Token::Required,
            "disabled" => Token::Disabled,
            "readonly" => Token::Readonly,
            "hidden" => Token::Hidden,
            "visible" => Token::Visible,
            "onclick" => Token::Onclick,
            "onsubmit" => Token::Onsubmit,
            "onchange" => Token::Onchange,
            // Layout Keywords
            "container" => Token::Container,
            "wrapper" => Token::Wrapper,
            "panel" => Token::Panel,
            "card" => Token::Card,
            "modal" => Token::Modal,
            "sidebar" => Token::Sidebar,
            "content" => Token::Content,
            "menu" => Token::Menu,
            "dropdown" => Token::Dropdown,
            "tooltip" => Token::Tooltip,
            "badge" => Token::Badge,
            "alert" => Token::Alert,
            "toast" => Token::Toast,
            "loading" => Token::Loading,
            "spinner" => Token::Spinner,
            // Control Flow Keywords
            "if" => Token::If,
            "then" => Token::Then,
            "else" => Token::Else,
            "otherwise" => Token::Otherwise,
            "when" => Token::When,
            "while" => Token::While,
            "loop" => Token::Loop,
            "for" => Token::For,
            "each" => Token::Each,
            "times" => Token::Times,
            "repeat" => Token::Repeat,
            "until" => Token::Until,
            "break" => Token::Break,
            "continue" => Token::Continue,
            "do" => Token::Do,
            "end" => Token::End,
            // Error Handling
            "try" => Token::Try,
            "catch" => Token::Catch,
            "throw" => Token::Throw,
            "error" => Token::Error,
            "finally" => Token::Finally,
            "raise" => Token::Raise,
            // Function Keywords
            "define" => Token::Define,
            "function" => Token::Function,
            "procedure" => Token::Procedure,
            "takes" => Token::Takes,
            "parameters" => Token::Parameters,
            "returns" => Token::Returns,
            "call" => Token::Call,
            "invoke" => Token::Invoke,
            "run" => Token::Run,
            "that" => Token::That,
            // Array & String Operations
            "push" => Token::Push,
            "pop" => Token::Pop,
            "filter" => Token::Filter,
            "map" => Token::Map,
            "sort" => Token::Sort,
            "reverse" => Token::Reverse,
            "length" => Token::Length,
            "contains" => Token::Contains,
            "first" => Token::First,
            "last" => Token::Last,
            "join" => Token::Join,
            "split" => Token::Split,
            "replace" => Token::Replace,
            "trim" => Token::Trim,
            "uppercase" => Token::Uppercase,
            "lowercase" => Token::Lowercase,
            "substring" => Token::Substring,
            "indexof" => Token::IndexOf,
            "concat" => Token::Concat,
            "concatenate" => Token::Concatenate,
            // Comparison Operators
            "equalto" => Token::EqualTo,
            "notequalto" => Token::NotEqualTo,
            "greaterthan" => Token::GreaterThan,
            "lessthan" => Token::LessThan,
            "greaterthanorequal" => Token::GreaterThanOrEqual,
            "lessthanorequal" => Token::LessThanOrEqual,
            "or" => Token::Or,
            "not" => Token::Not,
            _ => Token::Identifier(word.to_string()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keyword_recognition() {
        assert_eq!(Token::from_word("create"), Token::Create);
        assert_eq!(Token::from_word("database"), Token::Database);
        assert_eq!(Token::from_word("Create"), Token::Create); // case insensitive
        assert_eq!(Token::from_word("DATABASE"), Token::Database);
    }

    #[test]
    fn test_identifier() {
        match Token::from_word("mydb") {
            Token::Identifier(s) => assert_eq!(s, "mydb"),
            _ => panic!("Expected Identifier"),
        }
    }
}
